# **1. PROBLEM:**

You are provided with daily historical sales data. The dataset contains 5 .csv file, file description description below:

File descriptions
1. sales.csv: Daily historical data from January 2013 to October 2015 (6 columns):

* Dữ liệu lịch sử hàng ngày từ tháng 1 năm 2013 đến tháng 10 năm 2015 (6 cột):

  * date: Date in format dd/mm/yyyy.
  * date_block_num: A consecutive month number, used for convenience. January 2013 is 0,  February 2013 is 1,..., October 2015 is 33.
  * shop_id: Unique identifier of a shop.
  * item_id: Unique identifier of a product.
  * item_price: Current price of an item.
  * item_cnt_day: Number of products sold.

2. items_list_1.csv: Supplemental information about the items/products in list 1 (3 columns):

* Thông tin bổ sung về mặt hàng/sản phẩm trong danh sách 1 (3 cột):

  * item_name: Name of item.
  * item_id: Unique identifier of a product.
  * item_category_id: Unique identifier of item category.
3. items_list_2.csv: Supplemental information about the items/products in list 2 (3 columns):

* Thông tin bổ sung về mặt hàng/sản phẩm trong danh sách 2 (3 cột):

  * item_name: Name of item.
  * item_id: Unique identifier of a product.
  * item_category_id: Unique identifier of item category.
4. item_categories.csv: Supplemental information about the items categories (2 columns):

* Thông tin bổ sung về các hạng mục (2 cột):

  * item_category_id: Unique identifier of item category.
  * item_category_name: Name of item category.
5. shops.csv: Supplemental information about the shops (2 columns):

* Thông tin bổ sung về cửa hàng (2 cột):

  * shop_name: Name of shop.
  * shop_id: Unique identifier of a shop.

# **2. QUESTION**
1. How many items are there in **list 1**? in **list 2**? in **only list 1** (List the name of them)? in **only list 2** (List the name of them)? in both of the two lists (List the name of them)? Create the new csv file only contains the unique items from the two lists? (Name that file as items.csv)

2. How many **items** are there in the items.csv? How many of them contain **digits in name**? How many of them are **FIFA football game** items (contain "**FIFA**" in the name)?

3. How many **item categories** are there in the dataset? Which item category contain **highest number of items**? **lowest number of items**? List all items according to each item category. Calculate the average number of items in each category.

4. Which **item** has the **highest price** in each year? Which item has the lowest price in each year? Calculate the average price of each item in each year?

5. Which **item** has the **highest sales** in each year? Which item has the lowest sales in each year? Calculate the average sales of each item in each year?

# **3. SOLUTION**

**Step 1: Data Import**

In [112]:
import pandas as pd
import numpy as np

from pathlib import Path

In [113]:
# Data path
DATA_PATH = Path("/content/drive/MyDrive/Data sample/Predict_future_sales/predict_future_sales")
ITEM_CSV_1 = DATA_PATH / 'items_list_1.csv'
ITEM_CSV_2 = DATA_PATH / 'items_list_2.csv'
ITEM_CATEGORIES_CSV = DATA_PATH / 'item_categories.csv'
SALES_CSV = DATA_PATH / 'sales.csv'
SHOPS_CSV = DATA_PATH / 'shops.csv'

In [114]:
items_list_1_df = pd.read_csv(ITEM_CSV_1)
items_list_1_df.head()

,item_name,item_id,item_category_id
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40
1,!ABBYY FineReader 12 Professional Edition Full...,1,76
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40
4,***КОРОБКА (СТЕКЛО) D,4,40

In [115]:
items_list_2_df = pd.read_csv(ITEM_CSV_2)
items_list_2_df.head()

,item_name,item_id,item_category_id
0,"1С:Биологический конструктор 1.5 [PC, Цифровая...",470,78
1,1С:Бухгалтерия 8 (ред.3.0) как на ладони. Изд ...,471,49
2,1С:Бухгалтерия 8 (ред.3.0) как на ладони. Изд ...,472,49
3,1С:Бухгалтерия 8 (ред.3.0) как на ладони. Изд ...,473,49
4,1С:Бухгалтерия 8 КОРП: учет в головной организ...,474,49

In [116]:
item_categories_df = pd.read_csv(ITEM_CATEGORIES_CSV)
item_categories_df.head()

        item_category_name  item_category_id
0  PC - Гарнитуры/Наушники                 0
1         Аксессуары - PS2                 1
2         Аксессуары - PS3                 2
3         Аксессуары - PS4                 3
4         Аксессуары - PSP                 4

In [117]:
sales_df = pd.read_csv(SALES_CSV)
sales_df.head()

         date  date_block_num  shop_id  item_id  item_price  item_cnt_day
0  02.01.2013               0       59    22154      999.00           1.0
1  03.01.2013               0       25     2552      899.00           1.0
2  05.01.2013               0       25     2552      899.00          -1.0
3  06.01.2013               0       25     2554     1709.05           1.0
4  15.01.2013               0       25     2555     1099.00           1.0

In [118]:
shop_df = pd.read_csv(SHOPS_CSV)
shop_df.head()

                        shop_name  shop_id
0   !Якутск Орджоникидзе, 56 фран        0
1   !Якутск ТЦ "Центральный" фран        1
2                Адыгея ТЦ "Мега"        2
3  Балашиха ТРК "Октябрь-Киномир"        3
4        Волжский ТЦ "Волга Молл"        4

**Question 1:**
* How many items are there:
  * in **list 1**? in **list 2**?
  * in **only list 1** (List the name of them)? in **only list 2** (List the name of them)? in both of the two lists (List the name of them)?
* Create the new csv file only contains the unique items from the two lists? (Name that file as items.csv)

In [119]:
print("There are", len(items_list_1_df), "items in list 1")
print("There are", len(items_list_2_df), "items in list 2")

There are 13790 items in list 1
There are 13748 items in list 2

In [120]:
items_list_1_df.describe()

            item_id  item_category_id
count  13790.000000      13790.000000
mean   11773.628064         45.945323
std     6441.204046         15.068492
min        0.000000          0.000000
25%     6668.250000         37.000000
50%    13427.500000         40.000000
75%    16874.750000         58.000000
max    22169.000000         82.000000

In [121]:
items_list_1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13790 entries, 0 to 13789
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_name         13790 non-null  object
 1   item_id           13790 non-null  int64
 2   item_category_id  13790 non-null  int64
dtypes: int64(2), object(1)
memory usage: 323.3+ KB

In [122]:
items_list_2_df.describe()

            item_id  item_category_id
count  13748.000000      13748.000000
mean   10843.137038         47.104597
std     6748.580612         17.298280
min      470.000000          0.000000
25%     5109.750000         37.000000
50%    10591.500000         40.000000
75%    17177.250000         61.000000
max    22150.000000         83.000000

In [123]:
items_list_2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13748 entries, 0 to 13747
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_name         13748 non-null  object
 1   item_id           13748 non-null  int64
 2   item_category_id  13748 non-null  int64
dtypes: int64(2), object(1)
memory usage: 322.3+ KB

In [124]:
merged_df = pd.merge(items_list_1_df,
                     items_list_2_df,
                     on='item_id',
                     how='outer',
                     indicator=True
                    )
merged_df

,item_name_x,item_id,item_category_id_x,item_name_y,item_category_id_y,_merge
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40.0,NaN,NaN,left_only
1,!ABBYY FineReader 12 Professional Edition Full...,1,76.0,NaN,NaN,left_only
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40.0,NaN,NaN,left_only
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40.0,NaN,NaN,left_only
4,***КОРОБКА (СТЕКЛО) D,4,40.0,NaN,NaN,left_only
...,...,...,...,...,...,...
22165,"Ядерный титбит 2 [PC, Цифровая версия]",22165,31.0,NaN,NaN,left_only
22166,Язык запросов 1С:Предприятия [Цифровая версия],22166,54.0,NaN,NaN,left_only
22167,Язык запросов 1С:Предприятия 8 (+CD). Хрустале...,22167,49.0,NaN,NaN,left_only
22168,Яйцо для Little Inu,22168,62.0,NaN,NaN,left_only
22169,Яйцо дракона (Игра престолов),22169,69.0,NaN,NaN,left_only

In [125]:
def process_df(_df):
    # clear nan columns and column "_merge"
    _df = _df.dropna(axis=1).drop(columns='_merge')

    # remove _x and _y in column names
    rename_dict = dict()
    for col_name in _df.columns:
        if '_x' in col_name or '_y' in col_name:
            rename_dict[col_name] = col_name[:-2]

    new_df = _df.rename(columns=rename_dict)
    return new_df

In [126]:
items_only_list_1_df = merged_df[merged_df._merge == 'left_only']
items_only_list_1_df = process_df(items_only_list_1_df)
items_only_list_1_df

,item_name,item_id,item_category_id
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40.0
1,!ABBYY FineReader 12 Professional Edition Full...,1,76.0
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40.0
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40.0
4,***КОРОБКА (СТЕКЛО) D,4,40.0
...,...,...,...
22165,"Ядерный титбит 2 [PC, Цифровая версия]",22165,31.0
22166,Язык запросов 1С:Предприятия [Цифровая версия],22166,54.0
22167,Язык запросов 1С:Предприятия 8 (+CD). Хрустале...,22167,49.0
22168,Яйцо для Little Inu,22168,62.0
22169,Яйцо дракона (Игра престолов),22169,69.0

In [127]:
items_only_list_2_df = merged_df[merged_df["_merge"] == 'right_only']
items_only_list_2_df = process_df(items_only_list_2_df)
items_only_list_2_df

,item_id,item_name,item_category_id
474,474,1С:Бухгалтерия 8 КОРП: учет в головной организ...,49.0
475,475,1С:Бухгалтерия 8 ПРОФ на 5 польз. Поставка для...,73.0
476,476,1С:Бухгалтерия 8 ПРОФ на 5 польз. Поставка для...,73.0
477,477,1С:Бухгалтерия 8 ПРОФ. Поставка для розничного...,73.0
478,478,1С:Бухгалтерия 8 ПРОФ. Поставка для розничного...,73.0
...,...,...,...
22146,22146,Я-ЛЕГЕНДА WB (BD),37.0
22147,22147,Я-ЛЕГЕНДА WB (регион),40.0
22148,22148,Я-ЧЕТВЕРТЫЙ WD,40.0
22149,22149,Я-ЧЕТВЕРТЫЙ WD (регион),40.0
22150,22150,Я-ЧЕТВЕРТЫЙ (BD),37.0

In [128]:
item_both_list_df = merged_df[merged_df["_merge"] == 'both']
item_both_list_df = process_df(item_both_list_df)
item_both_list_df = item_both_list_df.loc[:,~item_both_list_df.columns.duplicated()]
item_both_list_df

,item_name,item_id,item_category_id
470,"1С:Биологический конструктор 1.5 [PC, Цифровая...",470,78.0
471,1С:Бухгалтерия 8 (ред.3.0) как на ладони. Изд ...,471,49.0
472,1С:Бухгалтерия 8 (ред.3.0) как на ладони. Изд ...,472,49.0
473,1С:Бухгалтерия 8 (ред.3.0) как на ладони. Изд ...,473,49.0
920,"1С:Школа. Химия, 8 кл.",920,77.0
...,...,...,...
21183,Футболка Minecraft Powered by Redstone черная S,21183,61.0
21184,Футболка Minecraft Run Away черная L,21184,61.0
21185,Футболка Minecraft Run Away черная M,21185,61.0
21186,Футболка Minecraft Run Away черная S,21186,61.0
21187,Футболка Minecraft Three Creeper Moon черная S,21187,61.0

In [129]:
print("There are", len(items_only_list_1_df), "items in only list 1")
print("There are", len(items_only_list_2_df), "items in only list 2")
print("There are", len(item_both_list_df), "items in both of the two lists")

There are 8422 items in only list 1
There are 8380 items in only list 2
There are 5368 items in both of the two lists

**Part 3: Create the new csv file only contains the unique items from the two lists? (Name that file as items.csv)**

**Step 1:** Create `items_df` DataFrame by concatenate 3 Dataframe (`item_only_list_1_df`; `item_only_list_2_df`, `item_both_list_df`)

**Step 2:** Save DataFrame to csv file

In [130]:
items_df = pd.concat([items_only_list_1_df, items_only_list_2_df, item_both_list_df])
items_df.to_csv('items.csv', index=False)
items_df

,item_name,item_id,item_category_id
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40.0
1,!ABBYY FineReader 12 Professional Edition Full...,1,76.0
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40.0
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40.0
4,***КОРОБКА (СТЕКЛО) D,4,40.0
...,...,...,...
21183,Футболка Minecraft Powered by Redstone черная S,21183,61.0
21184,Футболка Minecraft Run Away черная L,21184,61.0
21185,Футболка Minecraft Run Away черная M,21185,61.0
21186,Футболка Minecraft Run Away черная S,21186,61.0
21187,Футболка Minecraft Three Creeper Moon черная S,21187,61.0

**3.3. Question 2:**

* How many items are there in the items.csv? </br>
* How many of them contain digits in name? </br>
* How many of them are FIFA football game items (contain "FIFA" in the name)? </br>

In [131]:
print("There are", len(items_df), "items in items.csv")

There are 22170 items in items.csv

In [132]:
# Create check_digit function
def check_digits(name):
    for char in name:
        if char.isdigit():
            return True
    return False

In [133]:
items_df['is_digits_in_name'] = items_df["item_name"].apply(check_digits)
items_df

,item_name,item_id,item_category_id,is_digits_in_name
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40.0,False
1,!ABBYY FineReader 12 Professional Edition Full...,1,76.0,True
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40.0,False
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40.0,False
4,***КОРОБКА (СТЕКЛО) D,4,40.0,False
...,...,...,...,...
21183,Футболка Minecraft Powered by Redstone черная S,21183,61.0,False
21184,Футболка Minecraft Run Away черная L,21184,61.0,False
21185,Футболка Minecraft Run Away черная M,21185,61.0,False
21186,Футболка Minecraft Run Away черная S,21186,61.0,False
21187,Футболка Minecraft Three Creeper Moon черная S,21187,61.0,False

In [134]:
item_name_with_digits_df = items_df.loc[items_df['is_digits_in_name']]
item_name_with_digits_df

,item_name,item_id,item_category_id,is_digits_in_name
1,!ABBYY FineReader 12 Professional Edition Full...,1,76.0,True
7,***УДАР ПО ВОРОТАМ-2 (UNI) D,7,40.0,True
18,/БОМБА ДЛЯ НЕВЕСТЫ /2DVD/ D,18,40.0,True
19,/ЗОЛОТАЯ КОЛЛЕКЦИЯ м/ф-72,19,40.0,True
20,/ОДНАЖДЫ В КИТАЕ-2,20,40.0,True
...,...,...,...,...
21148,Футболка Mass Effect 3 Special Forces серая M,21148,61.0,True
21149,Футболка Mass Effect 3 Special Forces серая S,21149,61.0,True
21150,Футболка Mass Effect 3 Take Earth Back синяя M,21150,61.0,True
21163,Футболка Metal Gear Solid 5 FOX Black M,21163,61.0,True
21164,Футболка Metal Gear Solid 5 FOX Black XL,21164,61.0,True

In [135]:
print(f'There are {len(item_name_with_digits_df)} items with digits in item_name')

There are 11158 items with digits in item_name

In [136]:
# Create check_fifa function
def check_fifa(name):
    if 'FIFA' in name.upper():
        return True
    return False

In [137]:
items_df['is_fifa_in_name'] = items_df['item_name'].apply(check_fifa)

In [138]:
item_name_with_fifa_df = items_df[items_df['is_fifa_in_name']]
item_name_with_fifa_df

,item_name,item_id,item_category_id,is_digits_in_name,is_fifa_in_name
13398,"Комплект ""Microsoft Xbox 360 E 500GB"" + "" FIFA...",13398,15.0,True,True
13405,"Комплект ""Microsoft Xbox One 500GB (Day One Ed...",13405,16.0,True,True
13456,"Комплект «FIFA 13 [PS3, русская версия]» + Кам...",13456,2.0,True,True
13474,Комплект «Sony PS3 (320 Gb) (CECH-2508B) + игр...,13474,11.0,True,True
13482,Комплект «Sony PS3 Super Slim (500 Gb) (CECH-4...,13482,11.0,True,True
...,...,...,...,...,...
3368,FIFA2010 ЧЕМП.МИРА ПО ФУТБОЛУ (3D BD),3368,38.0,True,True
948,"2014 FIFA World Cup [PS3, английская версия]",948,19.0,True,True
949,"2014 FIFA World Cup [Xbox 360, английская версия]",949,23.0,True,True
950,"2014 FIFA World Cup. Champion's Edition [PS3, ...",950,19.0,True,True
951,2014 FIFA World Cup. Champion's Edition [Xbox ...,951,23.0,True,True

In [139]:
print(f'There are {len(item_name_with_fifa_df)} items with FIFA in item_name')

There are 79 items with FIFA in item_name

**3.4. Question 3:**

* How many **item categories** are there in the dataset?

* Which item category contain **highest number of items**? **lowest number of items**? List all items according to each item category. Calculate the average number of items in each category.

In [140]:
print('There are', len(item_categories_df),'categories in the dataset')

There are 84 categories in the dataset

In [141]:
items_df.head()

,item_name,item_id,item_category_id,is_digits_in_name,is_fifa_in_name
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40.0,False,False
1,!ABBYY FineReader 12 Professional Edition Full...,1,76.0,True,False
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40.0,False,False
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40.0,False,False
4,***КОРОБКА (СТЕКЛО) D,4,40.0,False,False

In [142]:
# Clear column "is_digits_in_name" and "is_fifa_in_name"
items_df.drop(columns=["is_digits_in_name", "is_fifa_in_name"], inplace=True)
items_df

,item_name,item_id,item_category_id
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40.0
1,!ABBYY FineReader 12 Professional Edition Full...,1,76.0
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40.0
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40.0
4,***КОРОБКА (СТЕКЛО) D,4,40.0
...,...,...,...
21183,Футболка Minecraft Powered by Redstone черная S,21183,61.0
21184,Футболка Minecraft Run Away черная L,21184,61.0
21185,Футболка Minecraft Run Away черная M,21185,61.0
21186,Футболка Minecraft Run Away черная S,21186,61.0
21187,Футболка Minecraft Three Creeper Moon черная S,21187,61.0

In [143]:
# Step 1: Create Dataframe merged_item_cat_df by merge items_df and item_categories_df. Parameter (how = "???", on = ???)
merged_item_cat_df = pd.merge(items_df, item_categories_df, how='left', on='item_category_id')
merged_item_cat_df.head()

,item_name,item_id,item_category_id,item_category_name
0,! ВО ВЛАСТИ НАВАЖДЕНИЯ (ПЛАСТ.) D,0,40.0,Кино - DVD
1,!ABBYY FineReader 12 Professional Edition Full...,1,76.0,Программы - Для дома и офиса (Цифра)
2,***В ЛУЧАХ СЛАВЫ (UNV) D,2,40.0,Кино - DVD
3,***ГОЛУБАЯ ВОЛНА (Univ) D,3,40.0,Кино - DVD
4,***КОРОБКА (СТЕКЛО) D,4,40.0,Кино - DVD

In [145]:
# Step 2: Create Dataframe grouped_merged_item_cat_df Group by which columns??? agg which columns and function agg???
grouped_merged_item_cat_df = merged_item_cat_df.groupby(
    by=['item_category_id', 'item_category_name']).agg({'item_id': list}).reset_index()
grouped_merged_item_cat_df.head()

,item_category_id,item_category_name,item_id
0,0.0,PC - Гарнитуры/Наушники,"[5441, 16255, 16256, 16257]"
1,1.0,Аксессуары - PS2,"[5606, 5740]"
2,2.0,Аксессуары - PS3,"[13069, 13070, 13411, 13414, 13456, 13459, 135..."
3,3.0,Аксессуары - PS4,"[13071, 5652, 5653, 5654, 5655, 5656, 5657, 56..."
4,4.0,Аксессуары - PSP,"[3111, 13101, 13102, 3666, 3667, 3668, 3669, 5..."

In [146]:
grouped_merged_item_cat_df.columns

Index(['item_category_id', 'item_category_name', 'item_id'], dtype='object')

In [147]:
# Step 3: Create column num_of_items in grouped_merged_item_cat_dfDataframe that have number of items by method?? function in method???
grouped_merged_item_cat_df['num_of_items'] = grouped_merged_item_cat_df['item_id'].apply(len)
grouped_merged_item_cat_df

,item_category_id,item_category_name,item_id,num_of_items
0,0.0,PC - Гарнитуры/Наушники,"[5441, 16255, 16256, 16257]",4
1,1.0,Аксессуары - PS2,"[5606, 5740]",2
2,2.0,Аксессуары - PS3,"[13069, 13070, 13411, 13414, 13456, 13459, 135...",75
3,3.0,Аксессуары - PS4,"[13071, 5652, 5653, 5654, 5655, 5656, 5657, 56...",34
4,4.0,Аксессуары - PSP,"[3111, 13101, 13102, 3666, 3667, 3668, 3669, 5...",15
...,...,...,...,...
79,79.0,Служебные,[17717],1
80,80.0,Служебные - Билеты,"[9244, 9246, 9248, 9250, 9252, 9254]",6
81,81.0,Чистые носители (шпиль),"[13346, 13347, 13349, 13352, 13355, 13356, 13358]",7
82,82.0,Чистые носители (штучные),"[13344, 13345, 13348, 13350, 13351, 13353, 133...",8
83,83.0,Элементы питания,"[22085, 22086, 22087, 22088, 22089, 22090, 220...",15

In [148]:
max_num_of_items_df = grouped_merged_item_cat_df[
    grouped_merged_item_cat_df["num_of_items"] == np.max(grouped_merged_item_cat_df["num_of_items"])]
max_num_of_items_df

,item_category_id,item_category_name,item_id,num_of_items
40,40.0,Кино - DVD,"[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15...",5035

In [149]:
min_num_of_items_df = grouped_merged_item_cat_df[
    grouped_merged_item_cat_df["num_of_items"] == np.min(grouped_merged_item_cat_df["num_of_items"])]
min_num_of_items_df

    item_category_id                 item_category_name  item_id  num_of_items
10              10.0              Игровые консоли - PS2   [6669]             1
51              51.0  Книги - Познавательная литература  [17703]             1
79              79.0                          Служебные  [17717]             1

In [150]:
print(f'Average number of items {np.average(grouped_merged_item_cat_df["num_of_items"])}')

Average number of items 263.92857142857144